### ISSUE TITLE
Niet accessible button gevonden

### ISSUE THREAD

**Issue by MicheleNL** [strexx/CSS-to-the-rescue#5]
<a class="closebtn" href="#">×</a> 
Kijk of je met de kennis van nu dit soort elementen semantischer en vriendelijker voor bijv. screen readers op kan zetten. Zie anders ook nog even de artikelen die je deze week moest lezen. 

Edit: ik zie nu dat dit eigenlijk de enige is!

**Comment by strexx** [comment]
Naar gekeken en toegepast waar mogelijk en waar nodig.

Ik heb nog wel iets gecomment in de HTML over de closeBtn van de overlay. Vraag is of dit ook een button moet zijn en zo ja, hoe laat ik hem dan sluiten zonder javascript te gebruiken.
